### PR TITLE
Increment 3: fix warnings in files

### LINKED ISSUE #186: fix(warnings): Increment 3. Fix files producing warnings.
Files in scope:
- ``StatisticsMT.cpp``
- ``ListExample1.cpp``
- ``PrimitiveGraph.cpp``

# Detailed Warnings

## CinderPeak/tests/unit/Statistics/StatisticsMT.cpp — 2 warning(s)

- **Line 85**: `unused variable ‘edges’ [-Wunused-variable]`
  - Category: **unused-variable**
  - Severity: **low**
  - Suggested fix: Remove the variable if not needed, or (if kept for debugging) prefix with UNUSED_ or (void)var; or mark [[maybe_unused]] (C++17) or use attribute((unused)). If variable is set but not used, check logic—maybe intended to be used or return it.

- **Line 184**: `unused variable ‘edges’ [-Wunused-variable]`
  - Category: **unused-variable**
  - Severity: **low**
  - Suggested fix: Remove the variable if not needed, or (if kept for debugging) prefix with UNUSED_ or (void)var; or mark [[maybe_unused]] (C++17) or use attribute((unused)). If variable is set but not used, check logic—maybe intended to be used or return it.

## CinderPeak/examples/CinderGraph/ListExample1.cpp:14 — 1 warning(s)

- **Line 18**: `declaration of ‘edge_weight’ shadows a member of ‘ListEdge’ [-Wshadow]`
  - Category: **shadowing**
  - Severity: **medium**
  - Suggested fix: Rename local variable to avoid shadowing, or qualify member access with this-> or class:: to make intent explicit. Alternatively, refactor to reduce scope of variable.

## CinderPeak/examples/CinderGraph/ListExample1.cpp:30 — 1 warning(s)

- **Line 8**: `structured binding declaration set but not used [-Wunused-but-set-variable]`
  - Category: **unused-variable**
  - Severity: **low**
  - Suggested fix: Remove the variable if not needed, or (if kept for debugging) prefix with UNUSED_ or (void)var; or mark [[maybe_unused]] (C++17) or use attribute((unused)). If variable is set but not used, check logic—maybe intended to be used or return it.

## CinderPeak/examples/CinderGraph/ListExample1.cpp:31 — 1 warning(s)

- **Line 8**: `structured binding declaration set but not used [-Wunused-but-set-variable]`
  - Category: **unused-variable**
  - Severity: **low**
  - Suggested fix: Remove the variable if not needed, or (if kept for debugging) prefix with UNUSED_ or (void)var; or mark [[maybe_unused]] (C++17) or use attribute((unused)). If variable is set but not used, check logic—maybe intended to be used or return it.

## CinderPeak/examples/CinderGraph/ListExample1.cpp:32 — 1 warning(s)

- **Line 8**: `structured binding declaration set but not used [-Wunused-but-set-variable]`
  - Category: **unused-variable**
  - Severity: **low**
  - Suggested fix: Remove the variable if not needed, or (if kept for debugging) prefix with UNUSED_ or (void)var; or mark [[maybe_unused]] (C++17) or use attribute((unused)). If variable is set but not used, check logic—maybe intended to be used or return it.

## CinderPeak/examples/CinderGraph/ListExample1.cpp:34 — 1 warning(s)

- **Line 8**: `structured binding declaration set but not used [-Wunused-but-set-variable]`
  - Category: **unused-variable**
  - Severity: **low**
  - Suggested fix: Remove the variable if not needed, or (if kept for debugging) prefix with UNUSED_ or (void)var; or mark [[maybe_unused]] (C++17) or use attribute((unused)). If variable is set but not used, check logic—maybe intended to be used or return it.

## CinderPeak/examples/CinderGraph/ListExample1.cpp:35 — 1 warning(s)

- **Line 8**: `structured binding declaration set but not used [-Wunused-but-set-variable]`
  - Category: **unused-variable**
  - Severity: **low**
  - Suggested fix: Remove the variable if not needed, or (if kept for debugging) prefix with UNUSED_ or (void)var; or mark [[maybe_unused]] (C++17) or use attribute((unused)). If variable is set but not used, check logic—maybe intended to be used or return it.

## CinderPeak/examples/CinderGraph/ListExample1.cpp:7 — 1 warning(s)

- **Line 18**: `declaration of ‘data’ shadows a member of ‘ListVertex’ [-Wshadow]`
  - Category: **shadowing**
  - Severity: **medium**
  - Suggested fix: Rename local variable to avoid shadowing, or qualify member access with this-> or class:: to make intent explicit. Alternatively, refactor to reduce scope of variable.

## CinderPeak/examples/CinderGraph/PrimitiveGraph.cpp:20 — 1 warning(s)

- **Line 8**: `variable ‘e2’ set but not used [-Wunused-but-set-variable]`
  - Category: **unused-variable**
  - Severity: **low**
  - Suggested fix: Remove the variable if not needed, or (if kept for debugging) prefix with UNUSED_ or (void)var; or mark [[maybe_unused]] (C++17) or use attribute((unused)). If variable is set but not used, check logic—maybe intended to be used or return it.

## CinderPeak/examples/CinderGraph/PrimitiveGraph.cpp:21 — 1 warning(s)

- **Line 8**: `variable ‘e3’ set but not used [-Wunused-but-set-variable]`
  - Category: **unused-variable**
  - Severity: **low**
  - Suggested fix: Remove the variable if not needed, or (if kept for debugging) prefix with UNUSED_ or (void)var; or mark [[maybe_unused]] (C++17) or use attribute((unused)). If variable is set but not used, check logic—maybe intended to be used or return it.

## CinderPeak/examples/CinderGraph/PrimitiveGraph.cpp:22 — 1 warning(s)

- **Line 8**: `variable ‘e4’ set but not used [-Wunused-but-set-variable]`
  - Category: **unused-variable**
  - Severity: **low**
  - Suggested fix: Remove the variable if not needed, or (if kept for debugging) prefix with UNUSED_ or (void)var; or mark [[maybe_unused]] (C++17) or use attribute((unused)). If variable is set but not used, check logic—maybe intended to be used or return it.

## CinderPeak/examples/CinderGraph/PrimitiveGraph.cpp:23 — 1 warning(s)

- **Line 8**: `variable ‘e5’ set but not used [-Wunused-but-set-variable]`
  - Category: **unused-variable**
  - Severity: **low**
  - Suggested fix: Remove the variable if not needed, or (if kept for debugging) prefix with UNUSED_ or (void)var; or mark [[maybe_unused]] (C++17) or use attribute((unused)). If variable is set but not used, check logic—maybe intended to be used or return it.

## CinderPeak/examples/CinderGraph/PrimitiveGraph.cpp:24 — 1 warning(s)

- **Line 8**: `variable ‘e6’ set but not used [-Wunused-but-set-variable]`
  - Category: **unused-variable**
  - Severity: **low**
  - Suggested fix: Remove the variable if not needed, or (if kept for debugging) prefix with UNUSED_ or (void)var; or mark [[maybe_unused]] (C++17) or use attribute((unused)). If variable is set but not used, check logic—maybe intended to be used or return it.

## CinderPeak/examples/CinderGraph/PrimitiveGraph.cpp:25 — 1 warning(s)

- **Line 8**: `variable ‘e7’ set but not used [-Wunused-but-set-variable]`
  - Category: **unused-variable**
  - Severity: **low**
  - Suggested fix: Remove the variable if not needed, or (if kept for debugging) prefix with UNUSED_ or (void)var; or mark [[maybe_unused]] (C++17) or use attribute((unused)). If variable is set but not used, check logic—maybe intended to be used or return it.

### PR DESCRIPTION
**Pull request by harveenkaur282-web**
## Which issue does this PR close?
- Closes #186 

## Rationale for this change
This PR resolves all compiler warnings reported in issue #186 across several files.
These warnings include unused variables, unused-but-set structured bindings, and member shadowing.
Fixing these warnings ensures cleaner builds and improves code readability and maintainability.

## What changes are included in this PR?
Fixed the warnings in the files, that were listed in the issue

## Are these changes tested?
Yes. The changes are applied only to unused variables and shadowed members.
All existing tests continue to pass, and the code compiles cleanly without warnings.

## Are there any user-facing changes?
No. These changes are internal code fixes and do not affect any public APIs or user-facing functionality.

### CODE REVIEW

File: examples/CinderGraph/PrimitiveGraph.cpp [hunk 1]
```diff
@@ -17,12 +17,12 @@ int main() {
 
   // Add cycle edges
   auto e1 = graph.addEdge(1, 2, 50);
-  graph.addEdge(2, 3, 60);
-  graph.addEdge(3, 4, 70);
-  graph.addEdge(4, 5, 80);
-  graph.addEdge(5, 6, 90);
-  graph.addEdge(6, 7, 100);
-  graph.addEdge(7, 8, 110);
+  (void)graph.addEdge(2, 3, 60);
```
Comment (SharonIV0x86) [inline examples/CinderGraph/PrimitiveGraph.cpp]: Why the ``void``?

Comment (harveenkaur282-web) [reply examples/CinderGraph/PrimitiveGraph.cpp]: ya, umm sorry the void casts were unnecessary, and so i have removed them for clarity and consistency.

**Review by SharonIV0x86 — APPROVED** [review]
LGTM.

Your PR has been approved and will be merged in sometime, till then if you like you can work on some new issue.

**Comment by SharonIV0x86** [comment]
@harveenkaur282-web 

Thank you for contributing, your PR has been merged.
